services:
  backend:
    build: .
    container_name: mrmikedevs_os_backend
    network_mode: "host"
    restart: always
    privileged: true
    volumes:
      - /:/host:ro
    environment:
      - DB_HOST=localhost
      - DB_PORT=15801
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mrmikedevs
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    network_mode: "host"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mrmikedevs
    command: ["postgres", "-p", "15801"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
