services:
  db:
    image: postgres:16-alpine
    container_name: mrmikedevs_os_db
    restart: always
    networks:
      - mrmikedevs_network
    ports:
      - "${DB_PORT:-15801}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-mrmikedev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mrmikedevsos}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mrmikedevs_os_pgadmin
    restart: always
    networks:
      - mrmikedevs_network
    ports:
      - "${PGADMIN_PORT:-15802}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: mrmikedevs_os_redis
    restart: unless-stopped
    networks:
      - mrmikedevs_network
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0
    ports:
      - "${REDIS_PORT:-15803}:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: mrmikedevs_os_redisinsight
    restart: unless-stopped
    networks:
      - mrmikedevs_network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${INTERNAL_REDIS_HOST}
      - REDIS_PORT=${INTERNAL_REDIS_PORT}
    ports:
      - "${RI_PORT:-15804}:5540"
    depends_on:
      - redis

networks:
  mrmikedevs_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: