name: Build & Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Reload Infrastructure
        run: |
          docker compose --env-file .env up -d --remove-orphans

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: go mod download

      - name: Build Backend Binary
        run: |
          sudo rm -rf bin/
          mkdir -p bin
          go build -buildvcs=false -o bin/mrmikedevs-backend .
      
      - name: Restart Systemd Service
        run: |
          sudo systemctl restart mrmikedevs-os-backend.service