name: Build & Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Rebuild & Deploy with Docker Compose
        run: docker compose --env-file .env up -d --build --remove-orphans